import Head from "next/Head";
import React, { useState, useEffect } from "react";
import Left from "../components/Left";
import Mid from "../components/Mid";
import Navbar from "../components/Navbar";
import Right from "../components/Right";
import styles from "../styles/Home.module.css";
import Files from "../components/Files";
import Folder from "../components/Folder";
import NavRouter from "../components/NavRouter";
import { useSelector, useDispatch } from "react-redux";
import axios from "axios";
import { useRouter } from "next/router";
import { currentFolder, recent } from "../redux/folderSlice";

const Folders = ({  }) => {
  const [fetchAgain, setFetchAgain] = useState(true);
  const router = useRouter();
  const dispatch = useDispatch();

  const userInfo = useSelector((state) => state.user.userInfo);
  const folder = useSelector((state) => state.folder.currentFolder);

//   useEffect(() => {
//     if (!userInfo) {
//       router.push("/login");
//     }

//     const fetch = async () => {
//       try {
//         const { data } = await axios.get(
//           `/api/folder/${router.query.id ? router.query.id : null}`,
//           {
//             headers: {
//               Authorization: `Bearer ${userInfo.token}`,
//             },
//           }
//         );
//         console.log({ folder });
//         dispatch(currentFolder(data));
//         // setFolder(data);
//         // dispatch(recent({ name: data.name, _id: data._id }));
//       } catch (error) {}
//     };

//     fetch();
//   }, [fetchAgain, id, dispatch]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Navbar />
        <div className={styles.main}>
          <div className={styles.left}>
            <Left />
          </div>
          <div className={styles.mid}>
            <NavRouter path={folder.path} current={folder.name} />
            <Folder folders={folder.folders} setFetchAgain={setFetchAgain} />
            <Files
              files={folder.files}
              inFolder={true}
              setFetchAgain={setFetchAgain}
            />
          </div>
          <div className={styles.right}>
            <Right />
          </div>
        </div>
      </div>
    </>
  );
};

export default Folders;

export async function getServerSideProps(context) {
//   const { params } = context;
//   const { id } = params;

  return {
    props: {  },
  };
}
